services:
  - type: web
    name: chat-ai-flux
    env: python
    region: virginia
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    pythonVersion: 3.10
